sudo: required
services:
 - docker
before_install:
 - docker build .
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 env: "DockerReact-env"
 bucket-name: "elasticbeanstalk-us-east-2-563953357779"
 bucket-path: "docker-react"
 on
  branch: master
  access_key_id: "AWS_ACCESS_KEY"
  secret_access_key: "AWS_SECRET_KEY"
