sudo: required
services:
 - docker
before_install:
 - docker build -t vmalse/docker-react -f Dockerfile.dev
script:
 - docker run vmalse/docker-react npm run test -- --coverage
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 github_token: $github_token
 env: "DockerReact-env"
 bucket-name: "elasticbeanstalk-us-east-2-563953357779"
 bucket-path: "docker-react"
 on
  branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
